@baseUrl = http://localhost:5000/api
@token = http://localhost:5000/api

POST {{baseUrl}}/auth/register
Content-Type: application/json
# Authorization: Bearer <your-token>

{
  "email": "beyndtech@gmail.com",
  "password": "justtesting",
  "accountType": "Patient"
}

###

GET {{baseUrl}}/auth/verify-email/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzYxOTQ5N2NhNTg0ZWRiYTYxZDY0MjMiLCJlbWFpbCI6ImJleW5kdGVjaEBnbWFpbC5jb20iLCJpYXQiOjE3MzQ0NDgyNzksImV4cCI6MTc2NTk4NDI3OX0.tsJDQ8UvdSn6TYNWdPTQvcFGJlFo1AwxWUzQ1VKlGfM
